#cloud-config
hostname: rancher-node2.example.com
rancher:
  network:
    dns:
      nameservers:
        - 172.16.0.1
      search:
        - example.com
    interfaces:
      eth0:
        address: 172.16.0.172/16
        gateway: 172.16.0.1
        mtu: 1500
        dhcp: false
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDi4sop1jRfwyfoPfQnUUrTJM2xFNi6s8Tzyfy8nWGNgDRWcuASDPXJce5hvo7AJBh+YUntkb6qlm+KVpXfzEiCAzTJoyYWQkYzVHzFYQvhqWsaGe2/JfzFroe3D/mVjPEdKHHaqwCHrIJjMlMGbF0f76k6Jgmximd56qo6cE803apZaNVAzjNtBfU5ng8J6t07kJGmQcdy/SpF4m4RQCFIgaunMl2zv1eO/0KL8Q1V/CTHtqdTbgNHeYaI6uD/Tow49lE7xEEZvgJ/BdM5W4wfd+2XqpYlPNK/jP2qYYeP+O1pRFgbZV0jmtnvNILVK36tvyQUXiUzp5TMyjJ/NnIM82SEfbwpqEGNkjvq3SI8b94eQB7O4d7dLAJusLQlVDcJO5kpYoAlhlKjFM1fUdRT+YWNyD/zCOGMVFP4ravT/gNRlM/inI83pAgcELj7UnsIyPVt90HF9on52vK5pyL42nTmT4ADrlL8sjhNgwKj0kQpk1pI74CW/Z7NM/fuc6stjrpDofael9Ie7FrSUjDAP7tARtVMct8HcX2580S9bIEZGYhYrOHZu0lNqAEggvOVohBWP8ABSVW18UgGapz8bDjPuwA5wGk5/90mo94D1knWk5MyhAIvUF9yicyRoe8GwKm/dlRRBzriBX6rgVJ6ce7d5NHH1MLEzgogZIk0Qw== rtcadm@infra.example.com
